# Generated by Django 5.0.6 on 2024-07-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_category_content_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.RemoveField(
            model_name='content',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='content',
            name='updated_at',
        ),
    ]
